/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // docSidebar: [{type: 'doc', dirName: '.'}],
  // docSidebar: [
  //   {
  //     type: 'doc',
  //     id:'简介'
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
  docs: [
    {
      type: 'category',
      label: '入门',
      collapsible: true,
      collapsed: false,
      items: [
        "简介", "快速预览", "搭建您的第一个编辑器", "搭建您的第一个引擎", "FAQ"
      ],
    },
    {
      type: 'category',
      label: '案例',
      collapsible: true,
      collapsed: false,
      items: [
        "搭建有事件响应和数据绑定的编辑器", "搭建使用了引擎的编辑器", "修改编辑器页面"
      ],
    },
    {
      type: 'category',
      label: '自定义',
      collapsible: true,
      collapsed: false,
      items: [
        "开发和发布扩展协议", "开发和发布扩展", "开发和发布贡献协议和贡献", "测试和调试扩展、贡献"
      ],
    },
  ],
};

module.exports = sidebars;
