/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // docSidebar: [{type: 'doc', dirName: '.'}],
  // docSidebar: [
  //   {
  //     type: 'doc',
  //     id:'简介'
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
  docs: [
    {
      type: 'category',
      label: '入门',
      collapsible: true,
      collapsed: false,
      items: [
        "简介", "创建第一个编辑器", "导入模板", "FAQ"
      ],
    },
    {
      type: 'category',
      label: '搭建编辑器',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: "概况",
          id: "搭建编辑器-概况"
        },
        {
          type: 'category',
          label: "示例",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'doc',
              label: "加入Material Inspector",
              id: "搭建编辑器-示例-加入Material Inspector"
            }
          ],
        },
        {
          type: 'category',
          label: "参考",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: "模板",
              collapsible: true,
              collapsed: false,
              items: [
                {
                  type: 'doc',
                  label: "完整的编辑器",
                  id: "搭建编辑器-参考-编辑器模板-完整的编辑器"
                }
              ],
            },
            {
              type: 'category',
              label: "UI Controls",
              collapsible: true,
              collapsed: false,
              items: [
                {
                  type: 'doc',
                  label: "概况",
                  id: "搭建编辑器-参考-UI Controls-概况"
                }
              ],
            },

          ],
        },
      ],
    },
    {
      type: 'category',
      label: '写代码',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: "概况",
          id: "写代码-概况"
        },
        {
          type: 'category',
          label: "参考",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'doc',
              label: "Package的API",
              id: "写代码-参考-Package的API"
            },
            {
              type: 'doc',
              label: "UI Control需要的数据的类型",
              id: "写代码-参考-UI Control需要的数据的类型"
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
